### ISSUE TITLE
add the github button 

### ISSUE THREAD

**Issue by pratap360** [pratap360/MyToolKits#15]
**for star/fork/contribute or simply check out the repo on github as in the nav bar before the How to use pop up**

![image](https://user-images.githubusercontent.com/52885495/196047587-738bc475-91ff-4fcc-8189-eb9ea7432575.png)

**Comment by treblig-punisher** [comment]
Hey Prat!  I am interested in working on this.

**Comment by CalArcher** [comment]
I am also interested in working on this :) @treblig-punisher do you mind if I take this as you just got assigned one haha? If not no problem

**Comment by treblig-punisher** [comment]
> 

Hey, go ahead and tackle this Cal.  Np :D

**Comment by pratap360** [comment]
so whom should I assign ? 🙄🤔

**Comment by treblig-punisher** [comment]
If Cal is still down for this, assign it to him.

**Comment by CalArcher** [comment]
Yes, thank you I would like to do it!

**Comment by CalArcher** [comment]
Okay and just to be clear, you would like the github icon on the nav bar, correct?

**Comment by pratap360** [comment]
> Okay and just to be clear, you would like the github icon on the nav bar, correct?

Yea you are right,but make sure while clicking the button it redirect to this repo as like other as 😅 also note use material style button and the GitHub icon within the button (refer for using materialized css - check out readme file )

**Comment by CalArcher** [comment]
Got it! Will get it done first thing tomorrow

**Comment by pratap360** [comment]
please also add ur github profile into about us page | contributors for more info read the [contributors.md](https://github.com/pratap360/MyToolKits/blob/main/CONTRIBUTING.md) file
