### ISSUE TITLE
Img Alt text

### ISSUE THREAD

**Issue by ibimina** [pratap360/MyToolKits#28]
- Describe your issue here in detail or in short also mention your where you found the issue...
No alt attribute in the IMG element in the index.html to make it accessible

**Comment by ibimina** [comment]
@pratap360 Kindly assign this to me
Thanks

**Comment by pratap360** [comment]
ok go for it

**Comment by pratap360** [comment]
please also add ur github profile into about us page | contributors

**Comment by ibimina** [comment]
Okay will do that now
