### ISSUE TITLE
Add custom scrollbar

### ISSUE THREAD

**Issue by bhattabhi013** [pratap360/MyToolKits#34]
- Describe your issue here in detail or in short also mention your where you found the issue...
Add custom scrollbar in the application to make it more attractive.

**Comment by pratap360** [comment]
which type of scrollbar are you talking about ?

**Comment by bhattabhi013** [comment]
Something like this.
<img width="19" alt="image" src="https://user-images.githubusercontent.com/47862474/197613374-3be419a8-e7dc-4f53-9d38-ef38353f18c0.png">

**Comment by pratap360** [comment]
Yea ok go for it but make sure you use materialized css components and match it according to the theme

**Comment by pratap360** [comment]
#40 done with the issue
