### ISSUE TITLE
Not having smooth transition in hover buttons

### ISSUE THREAD

**Issue by MohitNamdev22** [pratap360/MyToolKits#42]
The buttons and social media icons don't have smooth transitions on hover. Can you assign it to me?

![image](https://user-images.githubusercontent.com/89779447/198815728-5f20f8bb-11b9-4943-80d7-8b710637a43b.png)

**Comment by pratap360** [comment]
but why you have to add smooth transitions for no reason 🙄 you can try other issue as well
